### ISSUE TITLE
Not working on other computer with python not installed

### ISSUE THREAD

**Issue by WhiteHatEthicalHacker** [f4kedre4lity/Blank-Grabber#20]
I recently made an auto run usb with the grabber on the USB as the auto run program, it works with only python installed computers for me, am I autistic or right?

**Comment by noahmajors** [comment]
autorun usbs dont actually work with windows 10 or 11, because microsoft saw the feature as a huge security risk. many other users have no issues using blank on machines that do not have python installed, since the stub is actually packaged with python directly. the issue you're facing could either be an issue with your auto run software or just the fact that windows patched your method.

**Comment by noahmajors** [comment]
seems that autorun still works, but must be manually enabled by the target machine before attempting to execute a payload...
https://stackoverflow.com/questions/46270274/autorun-usb-in-windows-10
